### ISSUE TITLE
Correct attribution for yl-training

### ISSUE THREAD

**Issue by penalosa** [the-scouts/see-also#1]
Looks like a great collection of resources! Just to note that `penalosa/yl-training` is originally forked from @RyanT5's `RyanT5/yl-training` (and he's the maintainer of the site), so that might be the link to add to keep up to date.

**Comment by AA-Turner** [comment]
Thanks Sam - will correct. Good to see UoE representation xD

**Comment by AA-Turner** [comment]
Done - thanks for letting me know. And thanks to you/@RyanT5 for the tool - lmk if you want to know more about HQ digital/data/etc at any time

**Comment by RyanT5** [comment]
Hey Adam, thanks for this. I'd love to know more about this and if there is any way I can get involved to help out 😃

**Comment by AA-Turner** [comment]
Adam.Turner at cycscouts.org.uk // edi global address list (school of econ)
